version: '3'

services:
  redis:
    container_name: redis
    image: redislabs/redisearch:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis-volume:/data
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    ports:
      - "8100:8100"  # Backend is accessible on localhost:8100
    depends_on:
      - redis
    env_file:
      - .env
      - .open-ai-env
      - .langsmith-api-key
    environment:
      PORT: 8100
      REDIS_URL: "redis://redis:6379"
      KUBECONFIG: "/backend/kubeconfig.yaml"
      LANGCHAIN_TRACING_V2: "true"
    volumes:
      - /Users/ojasgosar/.kube:/root/.kube
      - /Users/ojasgosar/.minikube:/root/.minikube
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"  # Frontend is accessible on localhost:5173
    environment:
      VITE_BACKEND_URL: "http://backend:8100"